### PR TITLE
No git branch

### PR DESCRIPTION
**Pull request by hfiguiere**
- Don't use git branch
- Also add a commit where they are missing.

### CODE REVIEW

**Comment by hfiguiere** [comment]
The missing commit were deduced based on the last build attempt.

Note that master build has failed, so if this does too it might be the reason.

**Comment by hfiguiere** [comment]
bot, build

**Comment by felipeborges** [comment]
Thank you! It seems that the issue with libovf-glib is gone after the disable-shallow-clone option is set.

If you don't have anything else to discuss, I am happy to merge this.

**Comment by hfiguiere** [comment]
I haven't had the time to check that this build works. But if you are ok with it, go ahead.

The other changes are only pining commits so that the build is reproducible.

**Comment by felipeborges** [comment]
Yes, I have done a test drive of the build and it seems to work as expected. Cheers!

**Pull request merged**
