### PR TITLE
Add osinfo-db extension

### PR DESCRIPTION
**Pull request by felipeborges**
https://github.com/flathub/flathub/pull/1818

### CODE REVIEW

**Comment by Eonfge** [comment]
You'll need to create the extension endpoint. See for example:
https://github.com/flathub/org.gnome.Lollypop/blob/b200f6dc08440d56116d552e52842a382ec89f5f/org.gnome.Lollypop.json#L36

On line 36, I use a cleanup-command to create the folder where the osinfo-db extension should be mounted

**Comment by felipeborges** [comment]
@Eonfge https://github.com/flathub/flathub/pull/1818

**Comment by barthalion** [comment]
The directory where extension is mounted needs to exist in the app.

**Comment by felipeborges** [comment]
`/app/share/osinfo` always existed in the Boxes Flatpak.

**Pull request merged**
